name: "Deploy"
on: workflow_dispatch

jobs:
  deploy:
    name: "Deploy app"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: ./ci-deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.DELDICO_FLY_API_TOKEN }}
